### PR TITLE
Add setuptools

### PR DESCRIPTION
**Pull request by bryanwweber**
I like to work with these kinds of things as packages so they can be used in any folder, so I went and implemented that. Install it with `pip` or `python setup.py install`, or I'm going to build a conda package.  You can also use it as `python -m irrev_mech [options]` once its installed. I also wanted to make it compatible with Python 3, so I did that too. I didn't test it very thoroughly though, so I'm not sure if I broke anything with the compatibility update.

### CODE REVIEW

**Comment by kyleniemeyer** [comment]
This is great, thanks!

Yeah, I've historically not been good about making my Python code as packages, although I'm getting better about this (c.f. [eval_kinetic_models](https://github.com/kyleniemeyer/eval_kinetic_models)).

Of course, with (automatic) unit tests it would be much easier to make sure nothing broke... but since those aren't yet incorporated, I'll merge this once I play with it a bit.

**Comment by bryanwweber** [comment]
OK great, thanks! Obviously feel free to modify the setup.py with any additional metadata, I went pretty minimal, and I picked a more-or-less random version number. I also wasn't sure how you'd want to implement the `main` method, so I left it in `irrev_mech.py` but it might make more sense in `__main__.py`.

**Comment by kyleniemeyer** [comment]
OK—I expanded upon your changes in a new branch `bryanwweber-add-setuptools`; would you try that and see if it works the way you'd expect?

**Comment by bryanwweber** [comment]
I made a few comments, mostly meta stuff. I think everything should work (although I didn't actually test it); but I don't think you changed anything in the code itself, so everything should still work.

**Comment by kyleniemeyer** [comment]
Thanks for those comments—I made all your suggested changes, and will merge my new branch into master (and close this PR)

**Pull request closed without merging**
